root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ."
  entrypoint = "./tmp/server"
  args_bin = ["-addr", ":8080"]
  delay = 500
  exclude_dir = ["tmp"]
  include_ext = ["go"]
  kill_delay = "0s"
  rerun = false

[log]
  time = true

[color]
  main     = "magenta"
  watcher  = "cyan"
  build    = "yellow"
  runner   = "green"

[misc]
  clean_on_exit = true
